### PR TITLE
Added levels

### PR DESCRIPTION
**Pull request by fingerwarrior**
Added levels for every pokemon, completely client side using javascript, little(?) effect on client, almost no effect on server.
alt tt
#16

### CODE REVIEW

**Comment by dphuang2** [comment]
Hi, since the master branch update this pull request has received conflicts. Would you like to resolve them or me to take your procedure and implement them in the updated branch?

**Comment by fingerwarrior** [comment]
i'll  resolve them myself, expect a new pull request soon

**Comment by fingerwarrior** [comment]
is this fine now?

**Comment by dphuang2** [comment]
It looks good (even uses JavaScript to render client-side). But one problem is that when you switch your ordering, the levels disappear because you are only running this on "DOMContentLoaded" and the new implementation uses AJAX to just replace the "show-pokemon-container" div. Since adding levels is lower priority to refactoring the code, I am going to leave this to you to fix.

**Comment by fingerwarrior** [comment]
Oh, did not notice that, on it.

**Comment by dphuang2** [comment]
Awesome contribution, great job.

**Comment by Soilydude** [comment]
Hey, I'm pretty amateur at any kind of programming but I thought I'd play around with the app as a bit of a learning experience. I've been adding different methods of sorting such as sorting by Favorite and I wanted to add a sort by Level in. With the Favorite sort, it was easy to just add in `params[:stat] = "favorite"` but I can't find a specific variable attributed to level (I tried 'level', it didn't work :( ), is there anything like this that I can use?

**Pull request merged**
