### PR TITLE
PoGoBag windows installer

### PR DESCRIPTION
**Pull request by evilhawk00**
This branch only contains source of the installer.

### CODE REVIEW

**Comment by dphuang2** [comment]
It seems like you made a pull request to master that only consists of the Windows Installer which would mean that the master branch would be deleted. 

Could you try making a pull request that merges the current master and your source files?

**Comment by evilhawk00** [comment]
Okay I can fix that. I"ll push again.

 Actually I thought about this problem before.......pushing these files combined with master will cause users has to download extra  unnecessary large files when they clone the project.  I was thinking  that if it's possible to create a separated branch that co-exist and never merges with master ?

**Comment by dphuang2** [comment]
Yes, that is possible. 

I have created a new branch, "WindowsInstaller" where you can make a new pull request to.

**Comment by evilhawk00** [comment]
Files merged :)

**Pull request merged**
